[package]
name = "stoorts/stoorts"
version = "0.1.0"
authors = []

[dependencies]

[targets.lib]
path = "src"
mods = [
  "Stoorts",
  "Stoorts.HList",
  "Stoorts.Literal",
  "Stoorts.Parity",
  "Stoorts.Vector",
]
